### PR TITLE
Closes #72, fixed some style work for windows native api.

### LINKED ISSUE #72: Respect ANSICON environment variable on Windows
If environment variable ANSICON is set on Windows, the console is capable of ANSI sequences, so preferably use them.

What about this patch?

>  --- a/include/rang.hpp
>  +++ b/include/rang.hpp
>  @@ -205,6 +205,7 @@ namespace rang_implementation {
>          inline HANDLE getVersionDependentHandle()
>          {
>                  if (IsWindowsVersionOrGreater(10, 0, 0)) return nullptr;
>  \+               if (getenv("ANSICON")) return nullptr;
>                  return GetStdHandle(STD_OUTPUT_HANDLE);
>          }
>   

Sorry for the formatting, it seems markup is mocking up ...

### PR DESCRIPTION
**Pull request by kingseva**
Also added setWinTermMode and setControlMode functions.
Behaviour of control::forceColor is changed for Windows.

### CODE REVIEW

File: include/rang.hpp [hunk 1]
```diff
@@ -347,30 +471,37 @@ template <typename T>
...
+}
+
+inline void setControlMode(const control value) noexcept
+{
+    rang_implementation::controlMode() = value;
+}
+
+// This function should be deprecated, cause it affects all streams but not only "os" stream.
+// Use rang::setControlMode instead.
 inline std::ostream &operator<<(std::ostream &os, const rang::control value)
```
Comment (agauniyal) [inline include/rang.hpp]: we can remove this entirely because the next release would be `3.0` which can take breaking changes 😄

**Comment by agauniyal** [comment]
@kingseva This is great! What do you think about complete removal instead of depreciation of that `operator<<` overload?

**Comment by kingseva** [comment]
@agauniyal Hello! I'm agree to remove this operator. If i knew that i can change old API, then i would removed that operator immediately. We also should not forget about changing CI test that use this operator. I'm add commit to my branch, than Github should add it to this PR. If not i'm close this PR and open new. :smile:
